[versions]
agp = "8.9.0"
kotlin = "2.0.21"
insta = "1.9.11"

[libraries]
insta-camera = { group = "com.arashivision.sdk", name = "sdkcamera", version.ref = "insta" }
insta-media = { group = "com.arashivision.sdk", name = "sdkmedia", version.ref = "insta" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
